name: Build and Test News Site

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Inject NewsAPI Key into index.html
        run: |
          sed -i "s/REPLACE_WITH_SECRET_KEY/${{ secrets.NEWS_API_KEY }}/g" index.html

      - name: Install http-server for static serving
        run: npm install -g http-server

      - name: Start static server in background
        run: |
          nohup http-server -p 5000 &
          sleep 5

      - name: Test site availability
        run: curl --fail http://localhost:5000 || (echo "Site did not respond" && exit 1)
