name: Build and Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject API Key from secret
        run: |
          sed -i "s/REPLACE_WITH_SECRET_KEY/${{ secrets.ICA_SECRET }}/g" index.html

      # Optional: Upload built site artifact (commented out due to download error)
      # - name: Upload built site artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: built-site
      #     path: .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
