            - name: Setup Node.js environment
  uses: actions/setup-node@v3.9.1
  with:
    always-auth: false
    node-version: '18'                # Use Node.js v18
    architecture: 'x64'               # Default architecture
    check-latest: true                # Check for the latest patch version
    cache: 'npm'                      # Enable caching for npm
    cache-dependency-path: '**/package-lock.json'  # Cache dependencies if added later
